const fs=require('fs');
const originalReadFileSync=fs.readFileSync;
const script=`<style>
#pbPage{display:none}#pbPage.active{display:block}.pb-wrap{display:grid;gap:16px}.pb-hero,.pb-school-box,.pb-school-card,.pb-gallery{background:#fff;border:1px solid #dce2e8;border-radius:18px;padding:18px}.pb-hero{padding:22px}.pb-hero h1{margin:0;font-size:29px}.pb-school-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:14px}.pb-field label{display:block;font-size:12px;font-weight:900;margin-bottom:6px}.pb-select{width:100%;padding:12px;border:1px solid #d8dee5;border-radius:11px;background:#fff;font:inherit}.pb-school-head,.pb-gallery-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.pb-school-head h2,.pb-gallery-head h2{margin:0;font-size:20px}.pb-scroll{overflow-x:auto;-webkit-overflow-scrolling:touch;border:1px solid #dce2e8;border-radius:13px;margin-top:12px}.pb-table{border-collapse:collapse;min-width:max-content;width:100%}.pb-table th,.pb-table td{border-bottom:1px solid #e4e8ec;border-right:1px solid #e4e8ec;padding:10px 9px;text-align:center;vertical-align:middle}.pb-table th:first-child,.pb-table td:first-child{position:sticky;left:0;background:#f6f8fa;z-index:2;min-width:88px;font-weight:900}.pb-table th{background:#f6f8fa;font-size:12px;line-height:1.35;min-width:145px}.pb-status{width:130px;padding:9px 7px;border:1px solid #d8dee5;border-radius:9px;background:#fff;font:inherit;font-weight:800}.pb-status.s-done{background:#e9f7ef;border-color:#b8e2c8}.pb-status.s-edit{background:#fff0f0;border-color:#f0bcbc}.pb-status.s-color{background:#fff6e6;border-color:#f2d29b}.pb-status.s-rough,.pb-status.s-detail{background:#f1f5ff;border-color:#cbd7f4}.pb-hint{font-size:12px;color:#7d8791;margin:8px 0 0}.pb-gallery-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:14px}.pb-photo{border:1px solid #e0e5ea;border-radius:13px;overflow:hidden;background:#f5f7f9}.pb-photo img{width:100%;aspect-ratio:1/1;object-fit:cover;display:block}.pb-photo-meta{padding:10px}.pb-photo-meta b{display:block;font-size:13px}.pb-photo-meta span{display:block;color:#7d8791;font-size:11px;margin-top:3px}.pb-empty{padding:28px;text-align:center;color:#9199a1;border:1px dashed #d6dde5;border-radius:13px;margin-top:14px}.pb-modal{position:fixed;inset:0;background:#18212b99;display:none;align-items:center;justify-content:center;padding:14px;z-index:100000}.pb-modal.open{display:flex}.pb-modal-box{width:min(520px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:18px;padding:18px}.pb-modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.pb-hidden{display:none!important}@media(max-width:700px){.pb-school-grid{grid-template-columns:1fr}.pb-hero h1{font-size:25px}.pb-gallery-grid{grid-template-columns:1fr 1fr}.pb-table th{min-width:132px}.pb-status{width:120px}}
</style>
<div id="pbPage" class="page"><div class="pb-wrap"><section class="pb-hero"><p class="muted">PROBLEM BANK PROGRESS</p><h1>📚 문제은행 진행상황</h1><p class="muted">내가 준비하고 있는 문제은행을 한눈에 관리해보세요.</p></section><section class="pb-school-box"><h2 style="margin:0">문제은행 학교 선택</h2><div class="pb-school-grid" id="pbSchoolSelectors"></div><p class="pb-hint">최대 3개 학교를 선택할 수 있어요.</p></section><div id="pbSchoolTables"></div><section class="pb-gallery"><div class="pb-gallery-head"><div><h2>🖼️ 문제은행 작업 사진</h2><p class="muted" style="margin:5px 0 0">내가 그린 문제은행 그림을 사진으로 보관해보세요.</p></div><button class="btn primary" id="pbAddPhoto">＋ 사진 추가</button></div><input id="pbPhotoInput" type="file" accept="image/*" class="pb-hidden"><div id="pbGallery"></div></section></div></div><div id="pbPhotoModal" class="pb-modal"><div class="pb-modal-box"><h3 style="margin-top:0">사진 정보</h3><div class="field"><label>학교</label><select id="pbPhotoSchool" class="pb-select"></select></div><div class="field"><label>제시물</label><select id="pbPhotoPrompt" class="pb-select"></select></div><div id="pbPhotoPreview" style="margin-top:10px"></div><div class="pb-modal-actions"><button class="btn" id="pbPhotoCancel">취소</button><button class="btn primary" id="pbPhotoSave">사진 저장</button></div></div></div>
<script>(function(){
const SCHOOLS={
'강원(삼척)':['텀블러&도시락','물안경&스노우보드','스마트워치&이어폰'],
'남서울':['트리방울&스프링','볼트너트&깃털','머그컵&책','와인잔&수건','무당벌레&테니스공'],
'백석':['단추&국자','다트&손거울','주사위&볼링핀','줄자&와인잔','트라이앵글&병뚜껑'],
'상명(천안)':['테니스채&셔틀콕&스펀지','콘센트&돋보기&만년필','다트&탁구채+공&비커','쪼리신발&전구&나무기차','페인트롤러&나무톱&귤','안경&메모지+압정&호두','발레슈즈&톱니&아이스크림','해바라기&달걀껍질&앵무새','벼&동전&선인장','나사못&조개껍질&도토리','파&노트+펜&옥수수알맹이','리본&색종이+클립&아이스크림','식물줄기&라임&벽돌','옷핀&종이&풍선','파티장식 리본&나뭇잎&압정','줄자&연필&금붕어','모종삽&핑킹가위&양배추','와인따개+코르크&콘센트&수박','전화선&공책&브로콜리','판사봉&체리&물이 든 유리컵'],
'청주':['토마토&전기콘센트','스테이플러&실타래','선물상자&커터칼','벽돌&허리벨트','콜라&칫솔','금붕어&물안경','셔틀콕&줄자','목장갑&애견리드줄'],
'한양(에리카)':['가위&팽이','꼬리빗&오레오쿠키','나사못&종이컵','넥타이&합죽선','스페너&빨래집게','스프링&무선마우스','십자드라이버&무지편지봉투','주름스트로우&티백','철제옷걸이&탁구채','케이블타이&밥주걱','병따개&육각너트','손거울&자물쇠','에어캡&모종삽','달걀박스&병따개','연필깎이&주름스트로우'],
'호서':['사과&자물쇠','종이비행기&스카치테이프','테니스공&만년필','라임&분무기','자물쇠&전선']};
const STATUSES=['미진행','러프스케치','디테일스케치','채색중','완료','수정필요'];let key='guest',selected=[null,null,null],status={},photos=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const storageKey=()=>`greensum_problem_bank_v1_${key}`;
function load(){try{const x=JSON.parse(localStorage.getItem(storageKey())||'{}');selected=x.selected||[null,null,null];status=x.status||{};photos=x.photos||[]}catch(e){selected=[null,null,null];status={};photos=[]}}
function save(){localStorage.setItem(storageKey(),JSON.stringify({selected,status,photos}))}function current(){return selected.filter(Boolean)}
function renderSelectors(){const b=document.getElementById('pbSchoolSelectors');b.innerHTML=selected.map((v,i)=>`<div class="pb-field"><label>학교 선택 ${i+1}</label><select class="pb-select" data-slot="${i}"><option value="">학교를 선택해주세요</option>${Object.keys(SCHOOLS).map(s=>`<option value="${esc(s)}" ${v===s?'selected':''}>${esc(s)}</option>`).join('')}</select></div>`).join('');b.querySelectorAll('select').forEach(e=>e.onchange=()=>{selected[+e.dataset.slot]=e.value||null;save();renderTables();renderPhotoSelectors()})}
function cls(v){return {'완료':'s-done','수정필요':'s-edit','채색중':'s-color','러프스케치':'s-rough','디테일스케치':'s-detail','미진행':'s-none'}[v]||'s-none'}
function renderTables(){const b=document.getElementById('pbSchoolTables');b.innerHTML=current().map(s=>`<section class="pb-school-card"><div class="pb-school-head"><h2>🏫 ${esc(s)}</h2><span class="muted">${SCHOOLS[s].length}개 제시물</span></div><div class="pb-scroll"><table class="pb-table"><thead><tr><th>진행상황</th>${SCHOOLS[s].map(p=>`<th>${esc(p)}</th>`).join('')}</tr></thead><tbody><tr><td>현재 상태</td>${SCHOOLS[s].map(p=>{const k=s+'::'+p,v=status[k]||'미진행';return `<td><select class="pb-status ${cls(v)}" data-k="${esc(k)}">${STATUSES.map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}</select></td>`}).join('')}</tr></tbody></table></div><p class="pb-hint">↔ 표를 좌우로 밀어서 모든 제시물을 확인할 수 있어요.</p></section>`).join('');b.querySelectorAll('.pb-status').forEach(e=>e.onchange=()=>{status[e.dataset.k]=e.value;save();e.className='pb-status '+cls(e.value)})}
function renderPhotoSelectors(){const s=document.getElementById('pbPhotoSchool');if(!s)return;s.innerHTML=current().map(x=>`<option>${esc(x)}</option>`).join('');renderPrompts()}
function renderPrompts(){const s=document.getElementById('pbPhotoSchool').value,p=document.getElementById('pbPhotoPrompt');p.innerHTML=(SCHOOLS[s]||[]).map(x=>`<option>${esc(x)}</option>`).join('')}
function renderGallery(){const b=document.getElementById('pbGallery');if(!photos.length){b.innerHTML='<div class="pb-empty">아직 등록한 문제은행 그림이 없습니다.<br>「＋ 사진 추가」에서 사진을 올려보세요.</div>';return}b.innerHTML='<div class="pb-gallery-grid">'+photos.map((p,i)=>`<article class="pb-photo"><img src="${p.data}"><div class="pb-photo-meta"><b>${esc(p.prompt)}</b><span>${esc(p.school)} · ${esc(p.date)}</span><button class="btn" data-i="${i}" style="margin-top:8px">삭제</button></div></article>`).join('')+'</div>';b.querySelectorAll('[data-i]').forEach(e=>e.onclick=()=>{photos.splice(+e.dataset.i,1);save();renderGallery()})}
let pending=null;function openPhoto(f){pending=f;const r=new FileReader();r.onload=()=>{document.getElementById('pbPhotoPreview').innerHTML=`<img src="${r.result}" style="width:100%;max-height:260px;object-fit:contain;border-radius:12px;background:#f5f7f9">`;document.getElementById('pbPhotoModal').classList.add('open')};r.readAsDataURL(f)}
function showPage(){const page=document.getElementById('pbPage'),nav=document.getElementById('pbNav');document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));page.classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));nav.classList.add('active');load();renderSelectors();renderTables();renderPhotoSelectors();renderGallery();scrollTo(0,0)}
function boot(){const page=document.getElementById('pbPage'),side=document.querySelector('.side');if(!page||!side||document.getElementById('pbNav'))return;const nav=document.getElementById('pbNav');nav.onclick=showPage;fetch('/api/me',{credentials:'same-origin'}).then(r=>r.json()).then(x=>{if(x.user){key=x.user.username||x.user.id||'guest';load()}}).catch(()=>{});renderSelectors();renderTables();renderPhotoSelectors();renderGallery();document.getElementById('pbAddPhoto').onclick=()=>{if(!current().length)return alert('먼저 문제은행 학교를 선택해주세요.');document.getElementById('pbPhotoInput').click()};document.getElementById('pbPhotoInput').onchange=e=>{const f=e.target.files&&e.target.files[0];if(f)openPhoto(f);e.target.value=''};document.getElementById('pbPhotoSchool').onchange=renderPrompts;document.getElementById('pbPhotoCancel').onclick=()=>{pending=null;document.getElementById('pbPhotoModal').classList.remove('open')};document.getElementById('pbPhotoSave').onclick=()=>{if(!pending)return;const img=document.querySelector('#pbPhotoPreview img');photos.push({school:document.getElementById('pbPhotoSchool').value,prompt:document.getElementById('pbPhotoPrompt').value,date:new Date().toISOString().slice(0,10),data:img.src});save();pending=null;document.getElementById('pbPhotoModal').classList.remove('open');renderGallery()}}
function addNav(){if(!document.querySelector('.side')||document.getElementById('pbNav'))return;const n=document.createElement('div');n.id='pbNav';n.className='nav';n.dataset.page='problemBank';n.textContent='📚 문제은행';document.querySelector('.side').appendChild(n);boot()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addNav);else addNav();setTimeout(addNav,300);setTimeout(addNav,1000);})();</script>`;
fs.readFileSync=function(file,options){let content=originalReadFileSync.call(this,file,options);if(typeof file==='string'&&typeof content==='string'&&file.endsWith('/public/index.html'))content=content.replace('</body>',script+'</body>');return content};
